sudo: required

language: csharp
mono: none
solution: FinalProjectRegistration.sln

before_script:
  sudo snap install dotnet-sdk --channel=lts/stable --classic
  sudo snap alias dotnet-sdk.dotnet dotnet


script:
  - dotnet restore
  - dotnet build
  - dotnet test
