sudo: required

language: csharp
mono: none
solution: FinalProjectRegistration.sln

addons:
  snaps:
    - name: dotnet-sdk
    - channel: 3.1

before_script:
  sudo snap alias dotnet-sdk.dotnet dotnet


script:
  - dotnet restore
  - dotnet build
  - dotnet test
