sudo: required

language: csharp
mono: none
solution: FinalProjectRegistration.sln

addons:
  snaps:
    - dotnet-sdk --channel=lts/stable --classic

before_script:
  - sudo snap alias dotnet-sdk.dotnet dotnet


script:
  - dotnet restore
  - dotnet build
  - dotnet test
